## Numpy

In [21]:
import numpy as np
import pandas as pd
import cv2

In [3]:
print(np.__version__)

1.23.0


In [4]:
data = np.array([50,650,782,856,452,365,400,500,656])

In [5]:
type(data)

numpy.ndarray

In [6]:
data.ndim

1

In [7]:
data = np.array([[784,78569],[850,568956],[400,85746.25]])

In [8]:
print(data)

[[7.840000e+02 7.856900e+04]
 [8.500000e+02 5.689560e+05]
 [4.000000e+02 8.574625e+04]]


In [9]:
data

array([[7.840000e+02, 7.856900e+04],
       [8.500000e+02, 5.689560e+05],
       [4.000000e+02, 8.574625e+04]])

In [10]:
data.ndim

2

In [11]:
data.shape

(3, 2)

In [12]:
data.dtype

dtype('float64')

In [13]:
data.astype('float')

array([[7.840000e+02, 7.856900e+04],
       [8.500000e+02, 5.689560e+05],
       [4.000000e+02, 8.574625e+04]])

In [14]:
data = np.array([784,78569,859,568956,400,56])

In [15]:
data

array([   784,  78569,    859, 568956,    400,     56])

In [18]:
df = pd.DataFrame(data)

In [19]:
df

0
0     784
1   78569
2     859
3  568956
4     400
5      56

In [22]:
img = cv2.imread("/Users/satyadevtummala/Desktop/Screen Shot 2022-07-08 at 3.20.49 PM.png")

In [31]:
df = pd.DataFrame(img[:,:,2])

In [32]:
df.head()

0     1     2     3     4     5     6     7     8     9     ...  2130  \
0   238   238   238   238   238   238   238   238   238   238  ...   238   
1   240   240   240   240   240   240   240   240   240   240  ...   240   
2   241   241   241   241   241   241   241   241   241   241  ...   241   
3   242   242   242   242   242   242   242   242   242   242  ...   242   
4   243   243   243   243   243   243   243   243   243   243  ...   243   

   2131  2132  2133  2134  2135  2136  2137  2138  2139  
0   238   238   238   238   238   238   238   238   238  
1   240   240   240   240   240   240   240   240   240  
2   241   241   241   241   241   241   241   241   241  
3   242   242   242   242   242   242   242   242   242  
4   243   243   243   243   243   243   243   243   243  

[5 rows x 2140 columns]

In [33]:
df.sum(axis=1)

0       509320
1       513600
2       515740
3       517880
4       520020
         ...  
1345    544380
1346    544380
1347    544380
1348    451460
1349    451397
Length: 1350, dtype: int64

In [34]:
df.mean(axis=1)

0       238.000000
1       240.000000
2       241.000000
3       242.000000
4       243.000000
           ...    
1345    254.383178
1346    254.383178
1347    254.383178
1348    210.962617
1349    210.933178
Length: 1350, dtype: float64